source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LiquidFloatingActionButton_Example' do
  pod "LiquidFloatingActionButton"
end

target 'LiquidFloatingActionButton_Tests' do
  pod "LiquidFloatingActionButton"

  
end
